/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;

public class App {

    public static void main(String[] args) {

        LinkedList list = new LinkedList();
        list.insert(5);
        list.insert(4);
        list.insert(3);
        list.insert(2);
        list.insert(1);
        list.insertToTail(6);

        list.insertAfter(3, 0);
        list.insertBefore(3, 0);



        System.out.println("Linked List " + list.toString());
        System.out.println("Has 15? " + list.includes(15));
        System.out.println("Has 50? " + list.includes(50));
//        System.out.println("k = " + list.kthValue(6));


        LinkedList list1 = new LinkedList();
        list1.insert(2);
        list1.insert(3);
        list1.insert(1);
        System.out.println("Linked List1 " + list1.toString());

        LinkedList list2 = new LinkedList();
        list2.insert(4);
        list2.insert(9);
        list2.insert(5);
        System.out.println("Linked List2 " + list2.toString());

        LinkedList result = list.zipLists(list1, list2);
        System.out.println("Zipped Linked List " + result.toString());
        LinkedList list3 = new LinkedList();
        list3.insert(1);
        list3.insert(2);
        list3.insert(3);
        list3.insert(2);
        list3.insert(1);

        System.out.println("list3 : " +list3.toString());
//        System.out.println("list3 //: " +list3.reverse());
        System.out.println("Is Palindorme : " +list3.isPalindorme(list3));
        LinkedList list4 = new LinkedList();
        list4.insert(1);
        list4.insert(2);
        list4.insert(3);
        list4.insert(4);
        list4.insert(1);
        System.out.println("Is Palindorme : " +list4.isPalindorme(list4));
    }

}